allowBuilds:
  "@scarf/scarf": true
  core-js: true
  core-js-pure: true
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - oxlint-plugin-react-doctor@0.5.1
  - react-doctor@0.5.1
peerDependencyRules:
  allowedVersions:
    "react@>15": "19"
    "react-dom@>15": "19"
    "@types/react@>16": "19"
    "@types/react-dom@>16": "19"
    "dva-core@>1": "2"
    "less-loader@>10": "11"
    "postcss@>8": "8"
